### ISSUE TITLE
Зависимости модов

### ISSUE THREAD

**Issue by zziger** [zziger/supercow-mod#26]
Нужна поддержка зависимостей модов, исходя из списка идентификаторов в `manifest.yml`

### Пример использования

`mod1/manifest.yml`
```yml
id: mod1
deps:
  - mod2
```

`mod2/manifest.yml`
```yml
id: mod2
```
